services:
  lob:
    build: .
    restart: unless-stopped
    container_name: lob
    ports:
      - "1770:1770"
    environment:
      DB_TYPE: postgres
      DB_HOST: lob-db
      DB_PORT: "5432"
      DB_USER: lob
      DB_PASS: ${DB_PASS}
      DB_NAME: lob
    depends_on: 
      lob-db:
        condition: service_healthy

  lob-db:
    image: postgres:16
    container_name: lob-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: lob
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: lob
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lob -d lob"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  prometheus:
    image: prom/prometheus
    container_name: prometheus-lob
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana-lob
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_PASS}
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/lob-dashboard.json
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
volumes:
  prom_data: