{
 "title": "Limit Order Book dash",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active Sell Orders",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "lob_active_sell_orders", "legendFormat": "Active sell orders" }
   ]
  },
  {
   "title": "Total Trades",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    { "expr": "lob_total_trades", "legendFormat": "Total Trades" }
   ]
  },
  {
   "title": "Order Process Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    { "expr": "lob_order_latency_sum", "legendFormat": "Latency" }
   ]
  },
  {
   "title": "Active Buy Orders",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    { "expr": "lob_active_buy_orders", "legendFormat": "Active Buy orders" }
   ]
  },
  {
   "title": "Volume at Price Level",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "lob_volume_pl{side=\"1\"}",
     "legendFormat": "Buy {{price}}"
    },
    {
     "expr": "lob_volume_pl{side=\"2\"}",
     "legendFormat": "Sell {{price}}"
    }
   ]
  }
 ]
}